-- Seeded from data.ts
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_the_lobster_pot_provincetown', 
        'The Lobster Pot', 
        'The Lobster Pot', 
        'Provincetown', 
        'MA', 
        '', 
        'Seafood', 
        'Aloha', 
        'None', 
        'https://ptownlobsterpot.com', 
        '321 Commercial St, Provincetown, MA', 
        180, 
        'ABCC-12345', 
        'Liquor (Full)', 
        98, 
        '2024-05-15', 
        3, 
        4.6, 
        0, 
        'Outer Cape', 
        'Iconic neon sign, waterfront dining, famous lobster bisque.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_various_retail_dining_undefined', 
        'Various Retail/Dining', 
        'Various Retail/Dining', 
        '', 
        'MA', 
        '', 
        '', 
        '', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        NULL, 
        NULL, 
        0, 
        '', 
        '',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_whaling_storage_undefined', 
        'Whaling Storage', 
        'Whaling Storage', 
        '', 
        'MA', 
        '', 
        '', 
        '', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        NULL, 
        NULL, 
        0, 
        '', 
        '',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_the_canteen_provincetown', 
        'The Canteen', 
        'The Canteen', 
        'Provincetown', 
        'MA', 
        '', 
        'Casual', 
        'Square', 
        'Direct', 
        'https://thecanteenptown.com', 
        '225 Commercial St, Provincetown, MA', 
        60, 
        '', 
        '', 
        99, 
        '', 
        2, 
        4.7, 
        0, 
        'Outer Cape', 
        'Communal seating, lobster rolls, and cod banh mi.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_private_residence_retail_undefined', 
        'Private Residence/Retail', 
        'Private Residence/Retail', 
        '', 
        'MA', 
        '', 
        '', 
        '', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        NULL, 
        NULL, 
        0, 
        '', 
        '',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_spiritus_pizza_provincetown', 
        'Spiritus Pizza', 
        'Spiritus Pizza', 
        'Provincetown', 
        'MA', 
        '', 
        'Takeout', 
        'Toast', 
        'Toast', 
        '', 
        '', 
        0, 
        '', 
        '', 
        95, 
        '', 
        1, 
        4.5, 
        1, 
        'Outer Cape', 
        'Late-night staple, thin crust, local gathering spot.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_fanizzi_s_provincetown', 
        'Fanizzi''s', 
        'Fanizzi''s', 
        'Provincetown', 
        'MA', 
        '', 
        'Fine Dining', 
        'Micros', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        96, 
        '', 
        3, 
        4.6, 
        0, 
        'Outer Cape', 
        'Italian-American, dramatic dining room overhanging the harbor.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_sea_captain_s_home_undefined', 
        'Sea Captain''s Home', 
        'Sea Captain''s Home', 
        '', 
        'MA', 
        '', 
        '', 
        '', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        NULL, 
        NULL, 
        0, 
        '', 
        '',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_the_mews_restaurant___cafe_provincetown', 
        'The Mews Restaurant & Cafe', 
        'The Mews Restaurant & Cafe', 
        'Provincetown', 
        'MA', 
        '', 
        'Fine Dining', 
        'Toast', 
        'Toast', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        4, 
        4.8, 
        0, 
        'Outer Cape', 
        'Upscale waterfront dining and piano bar.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_kung_fu_dumplings_provincetown', 
        'Kung Fu Dumplings', 
        'Kung Fu Dumplings', 
        'Provincetown', 
        'MA', 
        '', 
        'Asian', 
        'Square', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.7, 
        1, 
        'Outer Cape', 
        'Specializes in handmade dumplings and noodles. Authentic street food vibe on Commercial St.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_sal_s_place_provincetown', 
        'Sal''s Place', 
        'Sal''s Place', 
        'Provincetown', 
        'MA', 
        '', 
        'Italian', 
        'Toast', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        3, 
        4.5, 
        1, 
        'Outer Cape', 
        'Historic Italian dining right on the beach in the West End.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_strangers___saints_provincetown', 
        'Strangers & Saints', 
        'Strangers & Saints', 
        'Provincetown', 
        'MA', 
        '', 
        'Gastropub', 
        'Toast', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        3, 
        4.7, 
        1, 
        'Outer Cape', 
        'Trendy Mediterranean tavern with craft cocktails.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_private_home_truro', 
        'Private Home', 
        'Private Home', 
        'Truro', 
        'MA', 
        '', 
        'Fine Dining', 
        'Aloha', 
        'None', 
        '', 
        '17 Truro Center Rd', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        4, 
        4.7, 
        1, 
        'Outer Cape', 
        'Upscale American restaurant in Truro Center. Refined menu.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_blacksmith_shop_undefined', 
        'Blacksmith Shop', 
        'Blacksmith Shop', 
        '', 
        'MA', 
        '', 
        '', 
        '', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        NULL, 
        NULL, 
        0, 
        '', 
        '',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_truro_vineyards__crush_pad__truro', 
        'Truro Vineyards (Crush Pad)', 
        'Truro Vineyards (Crush Pad)', 
        'Truro', 
        'MA', 
        '', 
        'Casual', 
        'Square', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.6, 
        1, 
        'Outer Cape', 
        'Winery with a dedicated food truck (Crush Pad) serving upscale snacks.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_truro_vineyards__lima__undefined', 
        'Truro Vineyards (Lima)', 
        'Truro Vineyards (Lima)', 
        '', 
        'MA', 
        '', 
        '', 
        '', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        NULL, 
        NULL, 
        0, 
        '', 
        '',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_historic_farmstead_undefined', 
        'Historic Farmstead', 
        'Historic Farmstead', 
        '', 
        'MA', 
        '', 
        '', 
        '', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        NULL, 
        NULL, 
        0, 
        '', 
        '',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_high_tide_kitchen_truro', 
        'High Tide Kitchen', 
        'High Tide Kitchen', 
        'Truro', 
        'MA', 
        '', 
        'Asian', 
        'Square', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.8, 
        1, 
        'Outer Cape', 
        'Asian fusion food truck in North Truro. A critical dining engine for the rural Outer Cape.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_savory___the_sweet_escape_truro', 
        'Savory & the Sweet Escape', 
        'Savory & the Sweet Escape', 
        'Truro', 
        'MA', 
        '', 
        'Casual', 
        'Toast', 
        'None', 
        '', 
        '1120 Cahoon Hollow Rd, Wellfleet, MA', 
        200, 
        'WLF-LIQ-001', 
        'Seasonal', 
        94, 
        '', 
        2, 
        4.4, 
        1, 
        'Outer Cape', 
        'Pizza, bakery, and ice cream spot along Route 6.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_cahoon_hollow_life_saving_station_undefined', 
        'Cahoon Hollow Life Saving Station', 
        'Cahoon Hollow Life Saving Station', 
        '', 
        'MA', 
        '', 
        '', 
        '', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        NULL, 
        NULL, 
        0, 
        '', 
        '',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_mac_s_shack_wellfleet', 
        'Mac''s Shack', 
        'Mac''s Shack', 
        'Wellfleet', 
        'MA', 
        '', 
        'Seafood', 
        'Toast', 
        'Toast', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        3, 
        4.7, 
        1, 
        'Outer Cape', 
        'Known for the freshest sushi and oysters on the outer cape.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_lobster_hutt_undefined', 
        'Lobster Hutt', 
        'Lobster Hutt', 
        '', 
        'MA', 
        '', 
        '', 
        '', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        NULL, 
        NULL, 
        0, 
        '', 
        '',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_pb_boulangerie_bistro_wellfleet', 
        'PB Boulangerie Bistro', 
        'PB Boulangerie Bistro', 
        'Wellfleet', 
        'MA', 
        '', 
        'Bakery/Bistro', 
        'Upserve', 
        'Direct', 
        'https://pbboulangeriebistro.com', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        3, 
        4.9, 
        0, 
        'Outer Cape', 
        'French bakery, legendary morning lines for croissants.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_a_w_undefined', 
        'A&W', 
        'A&W', 
        '', 
        'MA', 
        '', 
        '', 
        '', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        NULL, 
        NULL, 
        0, 
        '', 
        '',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_pizza_spinello_wellfleet', 
        'Pizza Spinello', 
        'Pizza Spinello', 
        'Wellfleet', 
        'MA', 
        '', 
        'Pizza', 
        'Toast', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.8, 
        1, 
        'Outer Cape', 
        'Seasonal, Roman-style pizza (al taglio) in a basement space on Main St. Cult favorite.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_various_seasonal_pop_ups_undefined', 
        'Various Seasonal Pop-ups', 
        'Various Seasonal Pop-ups', 
        '', 
        'MA', 
        '', 
        '', 
        '', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        NULL, 
        NULL, 
        0, 
        '', 
        '',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_fox___crow_cafe_wellfleet', 
        'Fox & Crow Cafe', 
        'Fox & Crow Cafe', 
        'Wellfleet', 
        'MA', 
        '', 
        'Cafe', 
        'Square', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        98, 
        '', 
        2, 
        4.6, 
        0, 
        'Outer Cape', 
        'Community cafe serving as a local gathering point year-round.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_nickerson_s_shell_station_undefined', 
        'Nickerson''s Shell Station', 
        'Nickerson''s Shell Station', 
        '', 
        'MA', 
        '', 
        '', 
        '', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        NULL, 
        NULL, 
        0, 
        '', 
        '',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_karoo_eastham', 
        'Karoo', 
        'Karoo', 
        'Eastham', 
        'MA', 
        '', 
        'International', 
        'Toast', 
        'Toast', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.6, 
        0, 
        'Outer Cape', 
        'South African cuisine, unique flavors on the Cape.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_fairway_pizzeria__partial__undefined', 
        'Fairway Pizzeria (partial)', 
        'Fairway Pizzeria (partial)', 
        '', 
        'MA', 
        '', 
        '', 
        '', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        NULL, 
        NULL, 
        0, 
        '', 
        '',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_good_eats_on_6_eastham', 
        'Good Eats on 6', 
        'Good Eats on 6', 
        'Eastham', 
        'MA', 
        '', 
        'Takeout', 
        'Clover', 
        'None', 
        '', 
        '38 Main St, Orleans, MA', 
        NULL, 
        '', 
        'Liquor (Full)', 
        NULL, 
        '', 
        2, 
        4.4, 
        0, 
        'Outer Cape', 
        'Roadside spot capturing transient beach traffic with high-quality takeout.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_news_shop___retail_undefined', 
        'News Shop / Retail', 
        'News Shop / Retail', 
        '', 
        'MA', 
        '', 
        '', 
        '', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        NULL, 
        NULL, 
        0, 
        '', 
        '',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_the_rail_orleans', 
        'The Rail', 
        'The Rail', 
        'Orleans', 
        'MA', 
        '', 
        'Bar/Pub', 
        'Toast', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.5, 
        0, 
        'Lower Cape', 
        'New tavern located in a converted railroad depot. Anchors the dining scene near the bike path.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_orleans_railroad_depot_undefined', 
        'Orleans Railroad Depot', 
        'Orleans Railroad Depot', 
        '', 
        'MA', 
        '', 
        '', 
        '', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        NULL, 
        NULL, 
        0, 
        '', 
        '',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_hole_in_one_orleans', 
        'Hole In One', 
        'Hole In One', 
        'Orleans', 
        'MA', 
        '', 
        'Bakery/Breakfast', 
        'Micros', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        1, 
        4.7, 
        0, 
        'Lower Cape', 
        'Famous for hand-cut donuts and hearty breakfasts.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_hog_island_beer_co__orleans', 
        'Hog Island Beer Co.', 
        'Hog Island Beer Co.', 
        'Orleans', 
        'MA', 
        '', 
        'Brewery', 
        'Toast', 
        'Toast', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.5, 
        0, 
        'Lower Cape', 
        'Brewery with outdoor games, food trucks, and local vibes.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_jailhouse_tavern__rear__chatham', 
        'Jailhouse Tavern (Rear)', 
        'Jailhouse Tavern (Rear)', 
        'Chatham', 
        'MA', 
        '', 
        'Fine Dining', 
        'Micros', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        100, 
        '', 
        4, 
        4.8, 
        0, 
        'Lower Cape', 
        'Oceanfront luxury, farm-to-table from their own farm.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_the_chatham_squire_chatham', 
        'The Chatham Squire', 
        'The Chatham Squire', 
        'Chatham', 
        'MA', 
        '', 
        'Bar/Pub', 
        'Aloha', 
        'None', 
        '', 
        '487 Main St, Chatham', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.3, 
        0, 
        'Lower Cape', 
        'License plates on walls, strong drinks, local legend.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_village_general_store_undefined', 
        'Village General Store', 
        'Village General Store', 
        '', 
        'MA', 
        '', 
        '', 
        '', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        NULL, 
        NULL, 
        0, 
        '', 
        '',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_bluefins_sushi___sake_bar_chatham', 
        'Bluefins Sushi & Sake Bar', 
        'Bluefins Sushi & Sake Bar', 
        'Chatham', 
        'MA', 
        '', 
        'Sushi', 
        'Toast', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        3, 
        4.7, 
        0, 
        'Lower Cape', 
        'High-end modern sushi and Asian fusion cuisine.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_hangar_b_eatery_chatham', 
        'Hangar B Eatery', 
        'Hangar B Eatery', 
        'Chatham', 
        'MA', 
        '', 
        'Breakfast', 
        'Square', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.8, 
        0, 
        'Lower Cape', 
        'Breakfast and lunch spot located at the Chatham Airport. Locals'' favorite.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_vernon_s_fish_market_undefined', 
        'Vernon''s Fish Market', 
        'Vernon''s Fish Market', 
        '', 
        'MA', 
        '', 
        '', 
        '', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        NULL, 
        NULL, 
        0, 
        '', 
        '',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_the_kitchen_cafe_brewster', 
        'The Kitchen Cafe', 
        'The Kitchen Cafe', 
        'Brewster', 
        'MA', 
        '', 
        'Cafe', 
        'Square', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.6, 
        0, 
        'Lower Cape', 
        'Focuses on healthy, fresh options. Counterpoint to fried fare.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_the_woodshed_brewster', 
        'The Woodshed', 
        'The Woodshed', 
        'Brewster', 
        'MA', 
        '', 
        'Bar/Pub', 
        'Aloha', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.3, 
        1, 
        'Lower Cape', 
        'Rustic bar/venue, famous dive bar atmosphere.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_scribano_s_italian_market_harwich', 
        'Scribano''s Italian Market', 
        'Scribano''s Italian Market', 
        'Harwich', 
        'MA', 
        '', 
        'Deli', 
        'Clover', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.8, 
        0, 
        'Lower Cape', 
        'The only source for ''real'' Italian subs on the Lower Cape. Import market and lunch counter.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_the_mad_minnow_harwich', 
        'The Mad Minnow', 
        'The Mad Minnow', 
        'Harwich', 
        'MA', 
        '', 
        'Gastropub', 
        'Toast', 
        'None', 
        '', 
        '357 Sesuit Neck Rd, Dennis', 
        NULL, 
        '', 
        'Common Victualler', 
        NULL, 
        '', 
        2, 
        4.6, 
        1, 
        'Lower Cape', 
        'Gastropub with a beer garden vibe in Harwich Port.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_municipal_boat_yard_undefined', 
        'Municipal Boat Yard', 
        'Municipal Boat Yard', 
        '', 
        'MA', 
        '', 
        '', 
        '', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        NULL, 
        NULL, 
        0, 
        '', 
        '',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_the_doghouse_dennis', 
        'The Doghouse', 
        'The Doghouse', 
        'Dennis', 
        'MA', 
        '', 
        'Fast Casual', 
        'Toast', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        1, 
        4.7, 
        1, 
        'Mid Cape', 
        'Dennis Port institution. Hot dog stand known for frosé and tater tot mountains.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_lune_dennis', 
        'Lune', 
        'Lune', 
        'Dennis', 
        'MA', 
        '', 
        'Fine Dining', 
        'Toast', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        4, 
        4.9, 
        0, 
        'Mid Cape', 
        'Modern dining with tasting menus. Semi-finalist for Best New Restaurant 2025 (James Beard).',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_the_red_pheasant__relocated__yarmouth', 
        'The Red Pheasant (Relocated)', 
        'The Red Pheasant (Relocated)', 
        'Yarmouth', 
        'MA', 
        '', 
        'Seafood', 
        'Aloha', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.4, 
        1, 
        'Mid Cape', 
        'Established 1936. Triple crown chowder winner.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_keltic_kitchen_yarmouth', 
        'Keltic Kitchen', 
        'Keltic Kitchen', 
        'Yarmouth', 
        'MA', 
        '', 
        'Breakfast', 
        'Micros', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.8, 
        0, 
        'Mid Cape', 
        'Beloved breakfast/brunch spot known for traditional Irish breakfast.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_inaho_yarmouth', 
        'Inaho', 
        'Inaho', 
        'Yarmouth', 
        'MA', 
        '', 
        'Sushi', 
        'Micros', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        3, 
        4.7, 
        0, 
        'Mid Cape', 
        'High-end Japanese/Sushi in a historic building in Yarmouth Port.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_the_karibbean_lounge_hyannis', 
        'The Karibbean Lounge', 
        'The Karibbean Lounge', 
        'Hyannis', 
        'MA', 
        '', 
        'International', 
        'Clover', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.6, 
        0, 
        'Mid Cape', 
        'Authentic Caribbean full-service restaurant. Jerk chicken, goat curry, oxtail.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_spoon_and_seed_hyannis', 
        'Spoon and Seed', 
        'Spoon and Seed', 
        'Hyannis', 
        'MA', 
        '', 
        'Breakfast', 
        'Toast', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.7, 
        0, 
        'Mid Cape', 
        'Farm-to-table breakfast and brunch spot.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_pizza_barbone_hyannis', 
        'Pizza Barbone', 
        'Pizza Barbone', 
        'Hyannis', 
        'MA', 
        '', 
        'Pizza', 
        'Toast', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.6, 
        0, 
        'Mid Cape', 
        'Wood-fired pizza with rooftop gardening. Authentic Neapolitan style.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_alberto_s_ristorante_hyannis', 
        'Alberto''s Ristorante', 
        'Alberto''s Ristorante', 
        'Hyannis', 
        'MA', 
        '', 
        'Italian', 
        'Micros', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        3, 
        4.5, 
        0, 
        'Mid Cape', 
        'Formal Northern Italian dining. A Hyannis staple.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_trevi_caf____wine_bar_mashpee', 
        'Trevi Café & Wine Bar', 
        'Trevi Café & Wine Bar', 
        'Mashpee', 
        'MA', 
        '', 
        'Wine Bar', 
        'Aloha', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        3, 
        4.6, 
        0, 
        'Upper Cape', 
        'European-style cafe with an extensive wine list and small plates.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_polar_cave_ice_cream_mashpee', 
        'Polar Cave Ice Cream', 
        'Polar Cave Ice Cream', 
        'Mashpee', 
        'MA', 
        '', 
        'Ice Cream', 
        'Clover', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        1, 
        4.8, 
        1, 
        'Upper Cape', 
        'Legendary shop known for made-to-order waffle cones.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_maison_villatte_falmouth', 
        'Maison Villatte', 
        'Maison Villatte', 
        'Falmouth', 
        'MA', 
        '', 
        'Bakery', 
        'Square', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.9, 
        0, 
        'Upper Cape', 
        'Highly regarded French bakery providing authentic pastries and breads.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_the_glass_onion_falmouth', 
        'The Glass Onion', 
        'The Glass Onion', 
        'Falmouth', 
        'MA', 
        '', 
        'Fine Dining', 
        'Toast', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        4, 
        4.7, 
        0, 
        'Upper Cape', 
        'Refined American cuisine in an intimate setting on North Main St.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_pickle_jar_kitchen_falmouth', 
        'Pickle Jar Kitchen', 
        'Pickle Jar Kitchen', 
        'Falmouth', 
        'MA', 
        '', 
        'Breakfast', 
        'Toast', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.7, 
        0, 
        'Upper Cape', 
        'Popular breakfast and lunch spot emphasizing wholesome ingredients.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_marshland_restaurant_sandwich', 
        'Marshland Restaurant', 
        'Marshland Restaurant', 
        'Sandwich', 
        'MA', 
        '', 
        'Diner', 
        'Micros', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        1, 
        4.5, 
        0, 
        'Upper Cape', 
        'Local institution famous for its comfort food and bakery (stuffed quahogs).',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_off_the_grid_sandwich', 
        'Off the Grid', 
        'Off the Grid', 
        'Sandwich', 
        'MA', 
        '', 
        'BBQ', 
        'Square', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.6, 
        0, 
        'Upper Cape', 
        'BBQ and craft beer spot adding a modern, casual trend.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_east_wind_lobster___grille_bourne', 
        'East Wind Lobster & Grille', 
        'East Wind Lobster & Grille', 
        'Bourne', 
        'MA', 
        '', 
        'Seafood', 
        'Aloha', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.5, 
        1, 
        'Upper Cape', 
        'Seafood market & eatery at Buzzards Bay Marina. Boat-to-table.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_mic_s_main_scoop_bourne', 
        'Mic''s Main Scoop', 
        'Mic''s Main Scoop', 
        'Bourne', 
        'MA', 
        '', 
        'Ice Cream', 
        'Clover', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        1, 
        4.6, 
        1, 
        'Upper Cape', 
        'Community-focused ice cream parlor in Buzzards Bay.',
        'prospect'
    );
INSERT OR REPLACE INTO restaurant_leads (
        id, name, dba_name, city, state, zip, 
        cuisine_primary, current_pos, online_ordering, website_url, 
        address_line1, actual_seat_count, license_number, license_type,
        health_score, last_inspection_date, price_level, google_rating,
        seasonal, region, notes, status
    ) VALUES (
        'lead_stir_crazy_bourne', 
        'Stir Crazy', 
        'Stir Crazy', 
        'Bourne', 
        'MA', 
        '', 
        'Asian', 
        'Toast', 
        'None', 
        '', 
        '', 
        NULL, 
        '', 
        '', 
        NULL, 
        '', 
        2, 
        4.5, 
        0, 
        'Upper Cape', 
        'Cambodian-influenced menu. Lock Lack beef and fresh maki rolls.',
        'prospect'
    );
